// Delete-reassign flows (PROMPT-05, 2026-09-16) — RESTRICT semantics for
// deleting a Person, a Pot or a Savings Pot (DECISIONS-2026-09-15.md Q5).
//
// Deleting any of the three is BLOCKED while anything still points at it.
// `findDeleteBlockers` lists what; `applyBlockerAction` resolves one item by
// reassigning it to an explicit, user-chosen target (never "the primary
// person") or deleting it. The Person/Pot/Savings Pot itself is only removed
// once the list is empty — see DeleteBlockedModal.
//
// Deliberately NOT restricted (Q5 items 3–4):
//  - CLEARED transactions are historical fact (APP-KNOWLEDGE §1.1). They
//    keep their ownerId/personId/potId/savingsPotId/fromLocation/toLocation
//    exactly as they are, and never block anything. `ON DELETE SET NULL` at
//    the database layer, later.
//  - Pending rows GENERATED by something (sourceType set, or a card's
//    minimum charge) follow their generator: reassigning the generator
//    rewrites them, deleting it sweeps them (lib/pendingSweep.ts). Only
//    hand-logged pending rows are listed individually.
//  - `locationHistory` entries are an audit trail, not live references.
//
// reconcilePersonReferences (lib/household.ts) stays the load-time
// self-healing backstop for imported/old data; this module is what stops
// the UI creating the dangling state in the first place.

import type { AppDataV2, CreditCard, Loan, RecurringTemplate, SalarySort, Transaction, TransferLocation } from '../types/ledger'
import type { BillLocation } from '../types/models'
import { reconcilePersonReferences } from './household'
import { priorLocationEntry, reassignCreditCardPaymentsForLocationChange, reassignTransactionsForLocationChange } from './locationChange'
import { reassignLoanRecurringOverpaymentTransactions } from './ledgerLoans'
import { sweepPendingForCreditCard, sweepPendingForLoan, sweepPendingForPot, sweepPendingForSavingsPot, sweepPendingForSource } from './pendingSweep'
import { categoryForTransfer, locationTypeForTransfer, transferLocationKey, transferLocationLabel, transferTouchesPot, transferTouchesSavingsPot } from './transferLedger'
import { toLocalIsoDate as toIso } from './date'

const todayIso = () => toIso(new Date())

// ── Salary Sort target removal (2026-09 session) — shared by
// updateTransaction (date-edit detach), removeTransaction (delete), and
// LedgerContext's own clearSalarySortTarget/saveSalarySort, so "drop one
// target, then remove the whole SalarySort if that empties it" is written
// exactly once. Pure — takes/returns the salarySorts array, no
// setDataState involved, so every caller composes it into their own
// single state update rather than this doing a second render pass.
// (Moved here from LedgerContext.tsx, which re-exports it.)
export function dropSalarySortTarget(salarySorts: SalarySort[], sortId: string, transactionId: string): SalarySort[] {
  return salarySorts
    .map((s) => (s.id === sortId ? { ...s, targets: s.targets.filter((t) => t.transactionId !== transactionId) } : s))
    .filter((s) => s.targets.length > 0)
}

// ── Plain removals — the state transforms behind LedgerContext's
// remove* mutations, shared with the blocker modal's "delete this item". ──

export function removeRecurringTemplateFromData(prev: AppDataV2, id: string, asOfIso: string = todayIso()): AppDataV2 {
  return {
    ...prev,
    recurringTemplates: prev.recurringTemplates.filter((t) => t.id !== id),
    transactions: sweepPendingForSource(prev.transactions, 'recurring_template', id, asOfIso),
  }
}

export function removeLoanFromData(prev: AppDataV2, id: string, asOfIso: string = todayIso()): AppDataV2 {
  const loan = prev.loans.find((l) => l.id === id)
  return {
    ...prev,
    loans: prev.loans.filter((l) => l.id !== id),
    transactions: loan ? sweepPendingForLoan(prev.transactions, loan, asOfIso) : prev.transactions,
  }
}

export function removeCreditCardFromData(prev: AppDataV2, id: string, asOfIso: string = todayIso()): AppDataV2 {
  return {
    ...prev,
    creditCards: prev.creditCards.filter((c) => c.id !== id),
    transactions: sweepPendingForCreditCard(prev.transactions, id, asOfIso),
  }
}

export function removePensionFromData(prev: AppDataV2, id: string, asOfIso: string = todayIso()): AppDataV2 {
  return {
    ...prev,
    pensions: prev.pensions.filter((p) => p.id !== id),
    transactions: sweepPendingForSource(prev.transactions, 'pension', id, asOfIso),
    // A person's followsIncomeSource pointing at a now-deleted pension
    // would silently strand their cycle-following choice — fall back
    // to 'salary' (the same default as never having set one), same
    // reconciliation instinct as household.ts's reconcilePersonReferences
    // for a dangling ownerId.
    payCycles: prev.payCycles.map((pc) =>
      pc.followsIncomeSource?.type === 'pension' && pc.followsIncomeSource.pensionId === id ? { ...pc, followsIncomeSource: { type: 'salary' } } : pc,
    ),
  }
}

export function removeTransactionFromData(prev: AppDataV2, id: string): AppDataV2 {
  const existing = prev.transactions.find((t) => t.id === id)
  const transactions = prev.transactions.filter((t) => t.id !== id)
  if (!existing || existing.sourceType !== 'salary_sort' || !existing.sourceId) {
    return { ...prev, transactions }
  }
  // Drops just this one target, leaving the rest of the sort intact
  // — matches saveSalarySort/clearSalarySortTarget's own "an empty
  // sort isn't a sort" rule if this was the last target.
  return { ...prev, transactions, salarySorts: dropSalarySortTarget(prev.salarySorts, existing.sourceId, id) }
}

export function removeLoanRecurringOverpaymentFromData(prev: AppDataV2, loanId: string, asOfIso: string = todayIso()): AppDataV2 {
  return {
    ...prev,
    loans: prev.loans.map((l) => (l.id === loanId ? { ...l, recurringOverpayment: undefined } : l)),
    transactions: prev.transactions.filter(
      (t) => !((t.status === 'pending' || t.date === asOfIso) && t.sourceType === 'loan_recurring_overpayment' && t.sourceId === loanId),
    ),
  }
}

export function removePersonFromData(prev: AppDataV2, id: string): AppDataV2 {
  if (prev.people.length <= 1) return prev // always at least one person
  const remaining = prev.people.filter((p) => p.id !== id)
  // With the delete guard in front of this, nothing should still point at
  // the person by now. reconcilePersonReferences still runs: it is what
  // turns a joint item into a personal one once fewer than 2 people are
  // left (Adam, 2026-09-16: joint bills reassigned at 100% move to
  // Personal when only one person remains), and it is the same backstop
  // every load/restore runs.
  return reconcilePersonReferences({
    ...prev,
    people: remaining,
    payCycles: prev.payCycles.filter((pc) => pc.personId !== id),
  })
}

export function removeSavingsPotFromData(prev: AppDataV2, id: string, asOfIso: string = todayIso()): AppDataV2 {
  // A pot's own CLEARED transactions (deposits/withdrawals/interest
  // already materialized) are historical fact and stay untouched —
  // same reasoning removePension uses for a person's past
  // pension_income transactions. PENDING ones are different: they
  // haven't happened yet and never will now, so they're swept
  // (2026-09 session — see sweepPendingForSavingsPot). The backstop then
  // clears anything else still pointing here (PROMPT-05 gaps 2–4), which
  // the delete guard should already have emptied.
  return reconcilePersonReferences({
    ...prev,
    savingsPots: prev.savingsPots.filter((p) => p.id !== id),
    transactions: sweepPendingForSavingsPot(prev.transactions, id, asOfIso),
  })
}

export function removePotFromData(prev: AppDataV2, id: string, asOfIso: string = todayIso()): AppDataV2 {
  return reconcilePersonReferences({
    ...prev,
    pots: prev.pots.filter((p) => p.id !== id),
    // A pot's own CLEARED transactions (deposits/withdrawals, and any
    // pot-funded bill/loan payment that already happened) are
    // historical fact and stay untouched — same reasoning
    // removeSavingsPot uses. PENDING ones are swept — they haven't
    // happened and never will now.
    transactions: sweepPendingForPot(prev.transactions, id, asOfIso),
    // Any bill/loan whose REGULAR payment pointed at this now-deleted
    // pot falls back to 'personal' rather than being left with a
    // dangling potId that nothing generates against. The delete guard
    // means the UI never reaches this with one still attached; kept for
    // any other caller. Recorded into locationHistory like any other
    // location change, so the Wallet page's audit trail shows WHY it moved.
    recurringTemplates: prev.recurringTemplates.map((t) =>
      t.location === 'pot' && t.potId === id
        ? {
            ...t,
            location: 'personal',
            potId: undefined,
            locationEffectiveFrom: asOfIso,
            locationHistory: [...(t.locationHistory ?? []), priorLocationEntry(t, t.anchorDate)],
          }
        : t,
    ),
    loans: prev.loans.map((l) => {
      let next = l
      if (l.location === 'pot' && l.potId === id) {
        next = {
          ...next,
          location: 'personal',
          potId: undefined,
          locationEffectiveFrom: asOfIso,
          locationHistory: [...(next.locationHistory ?? []), priorLocationEntry(next, next.startDate)],
        }
      }
      // A recurring overpayment independently funded from this pot
      // loses that explicit choice too — reverts to "follows the
      // loan's own location" (the field's own absent-default), not
      // forced to 'personal', since the loan itself might still be
      // pot-funded via a DIFFERENT pot, or genuinely personal/joint.
      if (next.recurringOverpayment?.location === 'pot' && next.recurringOverpayment.potId === id) {
        next = { ...next, recurringOverpayment: { ...next.recurringOverpayment, location: undefined, potId: undefined } }
      }
      return next
    }),
    // 2026-09-16 — a card whose minimum payment was paid from this pot.
    creditCards: prev.creditCards.map((c) => (c.location === 'pot' && c.potId === id ? relocateCreditCard(c, 'personal', undefined, asOfIso) : c)),
  })
}

// ── Blockers ────────────────────────────────────────────────────────────

export type DeleteSubject = { type: 'person'; id: string } | { type: 'pot'; id: string } | { type: 'savingsPot'; id: string }

export type BlockerGroup =
  | 'pensions'
  | 'savingsPots'
  | 'pots'
  | 'bills'
  | 'recurringTransactions'
  | 'recurringTransfers'
  | 'jointSplits'
  | 'loans'
  | 'loanRecurringOverpayments'
  | 'creditCards'
  | 'upcomingTransactions'
  | 'interestDestinations'

/** Display order and headings for the blocker modal. */
export const BLOCKER_GROUPS: { group: BlockerGroup; label: string }[] = [
  { group: 'pensions', label: 'Pensions' },
  { group: 'savingsPots', label: 'Savings pots' },
  { group: 'pots', label: 'Pots' },
  { group: 'bills', label: 'Bills' },
  { group: 'jointSplits', label: 'Joint account splits' },
  { group: 'loans', label: 'Loans' },
  { group: 'loanRecurringOverpayments', label: 'Recurring overpayments' },
  { group: 'creditCards', label: 'Credit cards' },
  { group: 'recurringTransactions', label: 'Recurring transactions' },
  { group: 'recurringTransfers', label: 'Recurring transfers' },
  { group: 'upcomingTransactions', label: 'Upcoming transactions' },
  { group: 'interestDestinations', label: 'Savings interest paid here' },
]

export type BlockerEntity = 'pension' | 'savingsPot' | 'pot' | 'template' | 'loan' | 'loanRecurringOverpayment' | 'creditCard' | 'transaction' | 'savingsPotInterest'

export interface DeleteBlocker {
  /** `${entity}:${id}` — stable across re-scans, so the UI can act on one. */
  key: string
  group: BlockerGroup
  entity: BlockerEntity
  id: string
  name: string
  detail?: string
}

export type BlockerTarget =
  | { type: 'person'; personId: string }
  | { type: 'location'; location: TransferLocation }
  /** A loan's recurring overpayment: go back to following the loan's own location. */
  | { type: 'followsLoan' }
  /** A savings pot's interest: back into the pot that earns it. */
  | { type: 'self' }

export interface BlockerTargetOption {
  key: string
  label: string
  target: BlockerTarget
}

export type BlockerAction = { type: 'reassign'; target: BlockerTarget } | { type: 'delete' }

function blocker(entity: BlockerEntity, group: BlockerGroup, id: string, name: string, detail?: string): DeleteBlocker {
  return { key: `${entity}:${id}`, group, entity, id, name, detail }
}

function templateGroup(t: RecurringTemplate): BlockerGroup {
  if (t.kind === 'transfer') return 'recurringTransfers'
  if (t.kind === 'transaction') return 'recurringTransactions'
  // APP-KNOWLEDGE §1.3 — a real bill's kind is undefined, never 'bill'.
  return 'bills'
}

/**
 * A joint item "involves" a person, for the purpose of blocking their delete, ONLY when they are
 * the named payee.
 *
 * 🚨 PROMPT-16 Part D3 (2026-09-22) — this used to be `payee === personId || payeeSharePercent <
 * 100`, i.e. any joint bill with a split at all. `costForPerson` (lib/bills.ts) gives every
 * NON-payee an equal slice of the remainder, so with three people a 50% split makes the third
 * person a 25% participant in every joint bill — which is true of the model, but it made deleting
 * a temporary third person list all NINE of Adam's real joint bills as "Temp pays 25%", each of
 * which he then had to "Move to Adam". The move set every share to 100 (below). Nine one-column
 * UPDATEs of `payee_share_percent`, owner untouched, no error anywhere, and his share of every
 * joint bill doubled in every projection.
 *
 * The remainder needs no reassignment when a non-payee leaves: it simply falls to whoever remains,
 * by the same formula. And when the payee leaves, taking the bill over does NOT change the split
 * (`reassignJointSplit`). The one place 100% is right is when a single person is left, where a
 * joint bill becomes personal — `reconcilePersonReferences`, unchanged (Adam, 2026-09-16, now
 * narrowed to that case with his agreement on 2026-09-22). verify-delete-reassign.ts carries the
 * control: the temporary-third-person case lists no joint bills.
 */
function jointItemInvolvesPerson(item: { location: BillLocation; payee: string; payeeSharePercent: number }, personId: string): boolean {
  return item.location === 'joint' && item.payee === personId
}

/** A pending row the user logged by hand, as opposed to one a generator owns. */
function isHandLoggedPending(t: Transaction): boolean {
  if (t.status !== 'pending') return false
  if (t.creditCardId) return false // generated minimum charges carry no sourceType
  return !t.sourceType || t.sourceType === 'salary_sort'
}

function transactionTouchesPot(t: Transaction, potId: string): boolean {
  return t.potId === potId || transferTouchesPot(t.fromLocation, t.toLocation, potId)
}

function transactionName(t: Transaction, data: AppDataV2): string {
  if (t.type === 'transfer') {
    return `${transferLocationLabel(t.fromLocation, data.savingsPots, data.pots)} → ${transferLocationLabel(t.toLocation, data.savingsPots, data.pots)}`
  }
  return t.note || 'Transaction'
}

const money = (n: number) => `£${n.toFixed(2)}`

export function findDeleteBlockers(data: AppDataV2, subject: DeleteSubject): DeleteBlocker[] {
  const out: DeleteBlocker[] = []

  if (subject.type === 'person') {
    const pid = subject.id
    for (const p of data.pensions ?? []) if (p.personId === pid) out.push(blocker('pension', 'pensions', p.id, p.name))
    for (const p of data.savingsPots ?? []) if (p.personId === pid) out.push(blocker('savingsPot', 'savingsPots', p.id, p.name))
    for (const p of data.pots ?? []) if (p.personId === pid) out.push(blocker('pot', 'pots', p.id, p.name))
    for (const t of data.recurringTemplates) {
      if (t.location === 'joint') {
        if (jointItemInvolvesPerson(t, pid)) out.push(blocker('template', 'jointSplits', t.id, t.name, splitDetail(data, t, pid)))
      } else if (t.ownerId === pid || t.personId === pid) {
        out.push(blocker('template', templateGroup(t), t.id, t.name))
      }
    }
    for (const l of data.loans) {
      if (l.location === 'joint') {
        if (jointItemInvolvesPerson(l, pid)) out.push(blocker('loan', 'jointSplits', l.id, l.name, splitDetail(data, l, pid)))
      } else if (l.ownerId === pid) {
        out.push(blocker('loan', 'loans', l.id, l.name, l.recurringOverpayment ? 'Includes its recurring overpayment' : undefined))
      }
    }
    for (const c of data.creditCards) if (c.ownerId === pid) out.push(blocker('creditCard', 'creditCards', c.id, c.name))
    for (const t of data.transactions) {
      if (isHandLoggedPending(t) && (t.ownerId === pid || t.personId === pid)) {
        out.push(blocker('transaction', 'upcomingTransactions', t.id, transactionName(t, data), `${money(t.amount)} on ${t.date}`))
      }
    }
    return out
  }

  if (subject.type === 'pot') {
    const potId = subject.id
    for (const t of data.recurringTemplates) {
      if (t.kind === 'transfer') {
        if (transferTouchesPot(t.transferFrom, t.transferTo, potId)) out.push(blocker('template', 'recurringTransfers', t.id, t.name, transferDetail(data, t)))
      } else if (t.location === 'pot' && t.potId === potId) {
        out.push(blocker('template', templateGroup(t), t.id, t.name))
      }
    }
    for (const l of data.loans) {
      if (l.location === 'pot' && l.potId === potId) out.push(blocker('loan', 'loans', l.id, l.name))
      if (l.recurringOverpayment?.location === 'pot' && l.recurringOverpayment.potId === potId) {
        out.push(blocker('loanRecurringOverpayment', 'loanRecurringOverpayments', l.id, l.name))
      }
    }
    // 2026-09-16 — a card's minimum payment can be paid from a pot.
    for (const c of data.creditCards) {
      if (c.location === 'pot' && c.potId === potId) out.push(blocker('creditCard', 'creditCards', c.id, c.name, 'Its minimum payment'))
    }
    for (const t of data.transactions) {
      if (isHandLoggedPending(t) && transactionTouchesPot(t, potId)) {
        out.push(blocker('transaction', 'upcomingTransactions', t.id, transactionName(t, data), `${money(t.amount)} on ${t.date}`))
      }
    }
    for (const s of data.savingsPots ?? []) {
      if (s.interestDestination?.type === 'pot' && s.interestDestination.potId === potId) out.push(blocker('savingsPotInterest', 'interestDestinations', s.id, s.name))
    }
    return out
  }

  const savingsPotId = subject.id
  for (const t of data.recurringTemplates) {
    if (t.kind === 'transfer' && transferTouchesSavingsPot(t.transferFrom, t.transferTo, savingsPotId)) {
      out.push(blocker('template', 'recurringTransfers', t.id, t.name, transferDetail(data, t)))
    }
  }
  for (const t of data.transactions) {
    // A pending row carrying this pot's own savingsPotId but no transfer
    // endpoint pointing here (a legacy savings_deposit) belongs to the
    // pot itself and is swept with it, so only transfers are listed.
    if (isHandLoggedPending(t) && t.type === 'transfer' && transferTouchesSavingsPot(t.fromLocation, t.toLocation, savingsPotId)) {
      out.push(blocker('transaction', 'upcomingTransactions', t.id, transactionName(t, data), `${money(t.amount)} on ${t.date}`))
    }
  }
  for (const s of data.savingsPots ?? []) {
    if (s.id !== savingsPotId && s.interestDestination?.type === 'savings' && s.interestDestination.savingsPotId === savingsPotId) {
      out.push(blocker('savingsPotInterest', 'interestDestinations', s.id, s.name))
    }
  }
  return out
}

function splitDetail(data: AppDataV2, item: { payee: string; payeeSharePercent: number }, personId: string): string {
  const name = (id: string) => data.people.find((p) => p.id === id)?.name ?? 'Someone'
  const share = item.payee === personId ? item.payeeSharePercent : 100 - item.payeeSharePercent
  return `${name(personId)} pays ${share}%`
}

function transferDetail(data: AppDataV2, t: RecurringTemplate): string {
  return `${transferLocationLabel(t.transferFrom, data.savingsPots, data.pots)} → ${transferLocationLabel(t.transferTo, data.savingsPots, data.pots)}`
}

// ── Target options ─────────────────────────────────────────────────────

function locationOption(data: AppDataV2, location: TransferLocation): BlockerTargetOption {
  const label = location.type === 'personal' ? 'Personal' : transferLocationLabel(location, data.savingsPots, data.pots)
  return { key: transferLocationKey(location), label, target: { type: 'location', location } }
}

function subjectLocationKey(subject: DeleteSubject): string | null {
  if (subject.type === 'pot') return `pot:${subject.id}`
  if (subject.type === 'savingsPot') return `savings:${subject.id}`
  return null
}

/** Where a pot-funded bill/loan (or its recurring overpayment) can move: Personal, or another of the owner's pots. */
function billLocationOptions(data: AppDataV2, ownerId: string, subject: DeleteSubject): BlockerTargetOption[] {
  const excluded = subjectLocationKey(subject)
  return [
    locationOption(data, { type: 'personal' }),
    ...(data.pots ?? []).filter((p) => p.personId === ownerId).map((p) => locationOption(data, { type: 'pot', potId: p.id })),
  ].filter((o) => o.key !== excluded)
}

/** Every transfer endpoint, minus the thing being deleted and minus `otherEnd` (a transfer can't go from somewhere to itself). */
function transferEndpointOptions(data: AppDataV2, subject: DeleteSubject, otherEnd: TransferLocation | undefined): BlockerTargetOption[] {
  const excluded = new Set([subjectLocationKey(subject), otherEnd ? transferLocationKey(otherEnd) : null])
  return [
    locationOption(data, { type: 'personal' }),
    ...(data.jointAccount ? [locationOption(data, { type: 'joint' })] : []),
    ...(data.savingsPots ?? []).map((p) => locationOption(data, { type: 'savings', savingsPotId: p.id })),
    ...(data.pots ?? []).map((p) => locationOption(data, { type: 'pot', potId: p.id })),
  ].filter((o) => !excluded.has(o.key))
}

function endpointMatchesSubject(location: TransferLocation | undefined, subject: DeleteSubject): boolean {
  return !!location && transferLocationKey(location) === subjectLocationKey(subject)
}

/** The endpoint of a transfer that is NOT the thing being deleted. */
function otherEndpoint(from: TransferLocation | undefined, to: TransferLocation | undefined, subject: DeleteSubject): TransferLocation | undefined {
  if (endpointMatchesSubject(from, subject)) return endpointMatchesSubject(to, subject) ? undefined : to
  return from
}

export function blockerTargetOptions(data: AppDataV2, subject: DeleteSubject, b: DeleteBlocker): BlockerTargetOption[] {
  if (subject.type === 'person') {
    return data.people.filter((p) => p.id !== subject.id).map((p) => ({ key: `person:${p.id}`, label: p.name, target: { type: 'person', personId: p.id } }))
  }

  switch (b.entity) {
    case 'template': {
      const t = data.recurringTemplates.find((x) => x.id === b.id)
      if (!t) return []
      if (t.kind === 'transfer') return transferEndpointOptions(data, subject, otherEndpoint(t.transferFrom, t.transferTo, subject))
      return billLocationOptions(data, t.ownerId, subject)
    }
    case 'loan': {
      const l = data.loans.find((x) => x.id === b.id)
      return l ? billLocationOptions(data, l.ownerId, subject) : []
    }
    case 'creditCard': {
      const c = data.creditCards.find((x) => x.id === b.id)
      return c ? billLocationOptions(data, c.ownerId, subject) : []
    }
    case 'loanRecurringOverpayment': {
      const l = data.loans.find((x) => x.id === b.id)
      if (!l) return []
      const loanStillHere = !(l.location === 'pot' && l.potId === subject.id)
      return [...(loanStillHere ? [{ key: 'followsLoan', label: 'Same as the loan', target: { type: 'followsLoan' } as BlockerTarget }] : []), ...billLocationOptions(data, l.ownerId, subject)]
    }
    case 'transaction': {
      const t = data.transactions.find((x) => x.id === b.id)
      if (!t) return []
      if (t.type === 'transfer') return transferEndpointOptions(data, subject, otherEndpoint(t.fromLocation, t.toLocation, subject))
      return billLocationOptions(data, t.ownerId, subject)
    }
    case 'savingsPotInterest': {
      const s = (data.savingsPots ?? []).find((x) => x.id === b.id)
      if (!s) return []
      const selfKey = `savings:${s.id}`
      return [
        { key: 'self', label: `Back into ${s.name}`, target: { type: 'self' } },
        ...transferEndpointOptions(data, subject, undefined).filter((o) => o.key !== selfKey),
      ]
    }
    default:
      return []
  }
}

/** Whether "delete this item" is offered. A pot/savings pot can only be deleted from here when nothing points at IT either. */
export function canDeleteBlocker(data: AppDataV2, b: DeleteBlocker): boolean {
  switch (b.entity) {
    case 'savingsPotInterest':
      return false
    case 'savingsPot':
      return findDeleteBlockers(data, { type: 'savingsPot', id: b.id }).length === 0
    case 'pot':
      return findDeleteBlockers(data, { type: 'pot', id: b.id }).length === 0
    default:
      return true
  }
}

// ── Applying an action ─────────────────────────────────────────────────

function swapPerson(t: Transaction, from: string, to: string): Transaction {
  if (t.ownerId !== from && t.personId !== from) return t
  return { ...t, ownerId: t.ownerId === from ? to : t.ownerId, personId: t.personId === from ? to : t.personId }
}

/** Rewrites the person on PENDING rows matching `belongs`; cleared rows are history and stay as they are. */
function swapPersonOnPending(transactions: Transaction[], belongs: (t: Transaction) => boolean, from: string, to: string): Transaction[] {
  return transactions.map((t) => (t.status === 'pending' && belongs(t) ? swapPerson(t, from, to) : t))
}

/** The payee is leaving: `to` takes the bill over with the split AS IT WAS (see jointItemInvolvesPerson). */
function reassignJointSplit<T extends { payee: string; payeeSharePercent: number }>(item: T, to: string): T {
  return { ...item, payee: to }
}

function reassignToPerson(data: AppDataV2, b: DeleteBlocker, from: string, to: string): AppDataV2 {
  switch (b.entity) {
    case 'pension':
      return {
        ...data,
        pensions: data.pensions.map((p) => (p.id === b.id ? { ...p, personId: to } : p)),
        transactions: swapPersonOnPending(data.transactions, (t) => t.sourceType === 'pension' && t.sourceId === b.id, from, to),
      }
    case 'savingsPot':
      return {
        ...data,
        savingsPots: data.savingsPots.map((p) => (p.id === b.id ? { ...p, personId: to } : p)),
        transactions: swapPersonOnPending(data.transactions, (t) => t.savingsPotId === b.id, from, to),
      }
    case 'pot':
      return {
        ...data,
        pots: data.pots.map((p) => (p.id === b.id ? { ...p, personId: to } : p)),
        transactions: swapPersonOnPending(data.transactions, (t) => t.potId === b.id, from, to),
      }
    case 'template':
      return {
        ...data,
        recurringTemplates: data.recurringTemplates.map((t) => {
          if (t.id !== b.id) return t
          if (t.location === 'joint') return reassignJointSplit(t, to)
          return { ...t, ownerId: t.ownerId === from ? to : t.ownerId, personId: t.personId === from ? to : t.personId }
        }),
        transactions: swapPersonOnPending(data.transactions, (t) => t.sourceType === 'recurring_template' && t.sourceId === b.id, from, to),
      }
    case 'loan': {
      const loan = data.loans.find((l) => l.id === b.id)
      const overpaymentIds = new Set(loan?.overpayments.map((o) => o.id) ?? [])
      return {
        ...data,
        loans: data.loans.map((l) => {
          if (l.id !== b.id) return l
          return l.location === 'joint' ? reassignJointSplit(l, to) : { ...l, ownerId: to }
        }),
        transactions: swapPersonOnPending(
          data.transactions,
          (t) =>
            ((t.sourceType === 'loan' || t.sourceType === 'loan_recurring_overpayment' || t.sourceType === 'loan_settlement') && t.sourceId === b.id) ||
            (t.sourceType === 'loan_overpayment' && overpaymentIds.has(t.sourceId ?? '')),
          from,
          to,
        ),
      }
    }
    case 'creditCard':
      return {
        ...data,
        creditCards: data.creditCards.map((c) => (c.id === b.id ? { ...c, ownerId: to } : c)),
        transactions: swapPersonOnPending(data.transactions, (t) => t.creditCardId === b.id, from, to),
      }
    case 'transaction':
      return { ...data, transactions: data.transactions.map((t) => (t.id === b.id ? swapPerson(t, from, to) : t)) }
    default:
      return data
  }
}

function replaceSubjectEndpoint(location: TransferLocation | undefined, subject: DeleteSubject, replacement: TransferLocation): TransferLocation | undefined {
  return endpointMatchesSubject(location, subject) ? replacement : location
}

/** Re-derives every field buildTransferTransaction computes from the two endpoints. */
function retargetTransferRow(t: Transaction, from: TransferLocation | undefined, to: TransferLocation | undefined): Transaction {
  if (!from || !to) return t
  return {
    ...t,
    fromLocation: from,
    toLocation: to,
    direction: from.type === 'personal' ? 'out' : 'in',
    categoryId: categoryForTransfer(from, to),
    location: locationTypeForTransfer(from, to),
    savingsPotId: from.type === 'savings' ? from.savingsPotId : to.type === 'savings' ? to.savingsPotId : undefined,
    potId: from.type === 'pot' ? from.potId : to.type === 'pot' ? to.potId : undefined,
  }
}

function billLocationOf(location: TransferLocation): { location: BillLocation; potId?: string } {
  return location.type === 'pot' ? { location: 'pot', potId: location.potId } : { location: 'personal' }
}

function relocateTemplate(t: RecurringTemplate, location: BillLocation, potId: string | undefined, asOfIso: string): RecurringTemplate {
  return {
    ...t,
    location,
    potId: location === 'pot' ? potId : undefined,
    locationEffectiveFrom: asOfIso,
    locationHistory: [...(t.locationHistory ?? []), priorLocationEntry(t, t.anchorDate)],
  }
}

function relocateLoan(l: Loan, location: BillLocation, potId: string | undefined, asOfIso: string): Loan {
  return {
    ...l,
    location,
    potId: location === 'pot' ? potId : undefined,
    locationEffectiveFrom: asOfIso,
    locationHistory: [...(l.locationHistory ?? []), priorLocationEntry(l, l.startDate)],
  }
}

function relocateCreditCard(c: CreditCard, location: 'personal' | 'pot', potId: string | undefined, asOfIso: string): CreditCard {
  return {
    ...c,
    location,
    potId: location === 'pot' ? potId : undefined,
    locationEffectiveFrom: asOfIso,
    locationHistory: [...(c.locationHistory ?? []), priorLocationEntry({ location: c.location ?? 'personal', potId: c.potId, locationEffectiveFrom: c.locationEffectiveFrom }, c.balanceAsOfDate)],
  }
}

/**
 * Keeps a rewrite on PENDING rows only. The Bills/Borrowing "move to a
 * pot" flow deliberately rewrites cleared rows from its effective date
 * (lib/locationChange.ts); a move made while deleting does not (Adam,
 * 2026-09-16): cleared rows are left alone, including one cleared today,
 * matching every other move in this file. Both lists are index-aligned
 * because the rewrite is a plain map.
 */
function pendingOnly(original: Transaction[], rewritten: Transaction[]): Transaction[] {
  return original.map((t, i) => (t.status === 'pending' ? rewritten[i] : t))
}

function reassignToLocation(data: AppDataV2, subject: DeleteSubject, b: DeleteBlocker, target: BlockerTarget, asOfIso: string): AppDataV2 {
  switch (b.entity) {
    case 'template': {
      const t = data.recurringTemplates.find((x) => x.id === b.id)
      if (!t || target.type !== 'location') return data
      if (t.kind === 'transfer') {
        const from = replaceSubjectEndpoint(t.transferFrom, subject, target.location)
        const to = replaceSubjectEndpoint(t.transferTo, subject, target.location)
        const updated: RecurringTemplate = { ...t, transferFrom: from, transferTo: to, location: locationTypeForTransfer(from, to), categoryId: categoryForTransfer(from, to) }
        return {
          ...data,
          recurringTemplates: data.recurringTemplates.map((x) => (x.id === t.id ? updated : x)),
          // Pending rows follow the new endpoints; cleared ones are history.
          transactions: data.transactions.map((row) =>
            row.status === 'pending' && row.sourceType === 'recurring_template' && row.sourceId === t.id
              ? retargetTransferRow(row, replaceSubjectEndpoint(row.fromLocation, subject, target.location), replaceSubjectEndpoint(row.toLocation, subject, target.location))
              : row,
          ),
        }
      }
      // Same shape as LedgerContext.assignRecurringTemplateLocation, effective today.
      const next = billLocationOf(target.location)
      return {
        ...data,
        recurringTemplates: data.recurringTemplates.map((x) => (x.id === t.id ? relocateTemplate(x, next.location, next.potId, asOfIso) : x)),
        transactions: pendingOnly(data.transactions, reassignTransactionsForLocationChange(data.transactions, 'recurring_template', t.id, asOfIso, next.location, next.potId)),
      }
    }
    case 'loan': {
      if (target.type !== 'location') return data
      const next = billLocationOf(target.location)
      return {
        ...data,
        loans: data.loans.map((l) => (l.id === b.id ? relocateLoan(l, next.location, next.potId, asOfIso) : l)),
        transactions: pendingOnly(data.transactions, reassignTransactionsForLocationChange(data.transactions, 'loan', b.id, asOfIso, next.location, next.potId)),
      }
    }
    case 'creditCard': {
      if (target.type !== 'location') return data
      const next = billLocationOf(target.location) as { location: 'personal' | 'pot'; potId?: string }
      return {
        ...data,
        creditCards: data.creditCards.map((c) => (c.id === b.id ? relocateCreditCard(c, next.location, next.potId, asOfIso) : c)),
        transactions: pendingOnly(data.transactions, reassignCreditCardPaymentsForLocationChange(data.transactions, b.id, asOfIso, next.location, next.potId)),
      }
    }
    case 'loanRecurringOverpayment': {
      const loan = data.loans.find((l) => l.id === b.id)
      if (!loan?.recurringOverpayment) return data
      const explicit = target.type === 'location' ? billLocationOf(target.location) : null
      const resolved = explicit ?? { location: loan.location, potId: loan.location === 'pot' ? loan.potId : undefined }
      return {
        ...data,
        loans: data.loans.map((l) =>
          l.id === b.id && l.recurringOverpayment
            ? {
                ...l,
                recurringOverpayment: {
                  ...l.recurringOverpayment,
                  location: explicit ? (explicit.location as 'personal' | 'pot') : undefined,
                  potId: explicit?.location === 'pot' ? explicit.potId : undefined,
                },
              }
            : l,
        ),
        transactions: pendingOnly(data.transactions, reassignLoanRecurringOverpaymentTransactions(data.transactions, b.id, asOfIso, resolved.location, resolved.potId)),
      }
    }
    case 'transaction': {
      const t = data.transactions.find((x) => x.id === b.id)
      if (!t || target.type !== 'location') return data
      if (t.type === 'transfer') {
        const from = replaceSubjectEndpoint(t.fromLocation, subject, target.location)
        const to = replaceSubjectEndpoint(t.toLocation, subject, target.location)
        const updated = retargetTransferRow(t, from, to)
        return {
          ...data,
          transactions: data.transactions.map((x) => (x.id === t.id ? updated : x)),
          // A Salary Sort target mirrors its transaction's destination.
          salarySorts:
            t.sourceType === 'salary_sort'
              ? data.salarySorts.map((s) => (s.id === t.sourceId ? { ...s, targets: s.targets.map((tg) => (tg.transactionId === t.id && to ? { ...tg, to } : tg)) } : s))
              : data.salarySorts,
        }
      }
      const next = billLocationOf(target.location)
      return { ...data, transactions: data.transactions.map((x) => (x.id === t.id ? { ...x, location: next.location, potId: next.potId } : x)) }
    }
    case 'savingsPotInterest':
      return {
        ...data,
        savingsPots: data.savingsPots.map((s) =>
          s.id === b.id ? { ...s, interestDestination: target.type === 'location' ? target.location : undefined } : s,
        ),
      }
    default:
      return data
  }
}

function deleteBlockerItem(data: AppDataV2, b: DeleteBlocker, asOfIso: string): AppDataV2 {
  switch (b.entity) {
    case 'pension':
      return removePensionFromData(data, b.id, asOfIso)
    case 'savingsPot':
      return removeSavingsPotFromData(data, b.id, asOfIso)
    case 'pot':
      return removePotFromData(data, b.id, asOfIso)
    case 'template':
      return removeRecurringTemplateFromData(data, b.id, asOfIso)
    case 'loan':
      return removeLoanFromData(data, b.id, asOfIso)
    case 'loanRecurringOverpayment':
      return removeLoanRecurringOverpaymentFromData(data, b.id, asOfIso)
    case 'creditCard':
      return removeCreditCardFromData(data, b.id, asOfIso)
    case 'transaction':
      return removeTransactionFromData(data, b.id)
    default:
      return data
  }
}

/**
 * Resolves one blocker. Re-scans first, so a stale key (already resolved,
 * or a target that is no longer valid) is a no-op rather than a bad write.
 */
export function applyBlockerAction(data: AppDataV2, subject: DeleteSubject, key: string, action: BlockerAction, asOfIso: string = todayIso()): AppDataV2 {
  const b = findDeleteBlockers(data, subject).find((x) => x.key === key)
  if (!b) return data
  if (action.type === 'delete') return canDeleteBlocker(data, b) ? deleteBlockerItem(data, b, asOfIso) : data

  const options = blockerTargetOptions(data, subject, b)
  const targetKey = targetOptionKey(action.target)
  if (!options.some((o) => o.key === targetKey)) return data

  if (subject.type === 'person') {
    return action.target.type === 'person' ? reassignToPerson(data, b, subject.id, action.target.personId) : data
  }
  return reassignToLocation(data, subject, b, action.target, asOfIso)
}

/** Reassigns every blocker that accepts `target` (the one-tap action). Blockers that don't accept it are left for the user. */
export function applyBlockerActionToAll(data: AppDataV2, subject: DeleteSubject, target: BlockerTarget, asOfIso: string = todayIso()): AppDataV2 {
  let next = data
  for (const b of findDeleteBlockers(data, subject)) {
    next = applyBlockerAction(next, subject, b.key, { type: 'reassign', target }, asOfIso)
  }
  return next
}

export function targetOptionKey(target: BlockerTarget): string {
  switch (target.type) {
    case 'person':
      return `person:${target.personId}`
    case 'location':
      return transferLocationKey(target.location)
    case 'followsLoan':
      return 'followsLoan'
    case 'self':
      return 'self'
  }
}

/**
 * The blocker sheet's Delete (Adam, 2026-09-16: "the move button should
 * store everything as a draft state"). Every Move/Delete choice in the sheet
 * is staged, and only this applies them — each decision in order, then the
 * delete itself, as one state update. If any blocker is still unresolved
 * afterwards, nothing at all is applied: a delete that can't complete must
 * not leave half its moves behind.
 */
export function resolveBlockersAndDelete(data: AppDataV2, subject: DeleteSubject, decisions: [key: string, action: BlockerAction][], asOfIso: string = todayIso()): AppDataV2 {
  let next = data
  for (const [key, action] of decisions) next = applyBlockerAction(next, subject, key, action, asOfIso)
  if (findDeleteBlockers(next, subject).length > 0) return data
  if (subject.type === 'person') return removePersonFromData(next, subject.id)
  if (subject.type === 'pot') return removePotFromData(next, subject.id, asOfIso)
  return removeSavingsPotFromData(next, subject.id, asOfIso)
}
