// ─────────────────────────────────────────────────────────────────────────
// The "invisible" icon library — a much larger pool of icons used ONLY to
// suggest an icon when the user creates a brand-new category. These never
// appear as a permanent, always-visible part of the icon set the way
// BILL_ICONS (billIcons.ts) does — the 35 icons there stay exactly as they
// are, unchanged, forever, so existing categories never shift meaning.
//
// Each entry here is offered as a suggestion at most once: once a category
// (built-in, seeded, or user-created) is actually using a given icon key,
// it's excluded from future suggestions — see availableExtendedIcons() in
// iconSuggestions.ts, which computes "used" live from the current category
// list rather than tracking a separate persisted flag. That also means an
// icon quietly becomes available again if the category using it is ever
// deleted, which is intentional (see that file's header comment).
//
// Every icon name here was checked against the installed lucide-react
// package's actual named exports before being added — don't add a new
// entry without doing the same (some very-plausible-sounding icon names,
// e.g. a dedicated "Tennis" or "Basketball" icon, don't exist in the
// library and will break the build).
// ─────────────────────────────────────────────────────────────────────────

import {
  Wine,
  Beer,
  Pizza,
  IceCream,
  Cake,
  Sandwich,
  Popcorn,
  Cookie,
  Apple,
  Banana,
  Fish,
  Egg,
  Salad,
  Soup,
  Croissant,
  Bike,
  Trophy,
  Medal,
  Target,
  Swords,
  Tent,
  Mountain,
  MountainSnow,
  Waves,
  Footprints,
  Volleyball,
  Ticket,
  Clapperboard,
  Camera,
  Palette,
  Paintbrush,
  Book,
  BookOpen,
  Library,
  Newspaper,
  Radio,
  Headphones,
  Mic,
  Guitar,
  Laptop,
  Monitor,
  Printer,
  HardDrive,
  Lightbulb,
  Plug,
  Thermometer,
  Fan,
  Refrigerator,
  WashingMachine,
  Sofa,
  Bed,
  Lamp,
  Hammer,
  Drill,
  PaintRoller,
  Ruler,
  Scissors,
  Sparkles,
  Bath,
  Cat,
  Dog,
  Bird,
  Rabbit,
  HeartHandshake,
  Gift,
  PartyPopper,
  HandCoins,
  Coins,
  DollarSign,
  PoundSterling,
  TrendingUp,
  TrendingDown,
  BarChart,
  Building,
  Briefcase,
  Package,
  Boxes,
  Store,
  ShoppingBag,
  Bus,
  TrainFront,
  Ship,
  Anchor,
  Sailboat,
  ParkingCircle,
  Sun,
  Cloud,
  Snowflake,
  Umbrella,
  Flower,
  Leaf,
  TreePine,
  Bug,
  FileText,
  Folder,
  Mail,
  Send,
  MessageCircle,
  Calendar,
  Clock,
  MapPin,
  Globe,
  Key,
  Lock,
  ShieldCheck,
  School,
  Backpack,
  type LucideIcon,
} from 'lucide-react'

export interface ExtendedIconEntry {
  icon: LucideIcon
  keywords: string[]
}

export const EXTENDED_ICONS: Record<string, ExtendedIconEntry> = {
  // ── Food & drink ──
  wine: { icon: Wine, keywords: ['wine', 'vineyard', 'drinks', 'alcohol', 'bar'] },
  beer: { icon: Beer, keywords: ['beer', 'pub', 'drinks', 'alcohol', 'bar', 'brewery'] },
  pizza: { icon: Pizza, keywords: ['pizza', 'takeaway', 'takeout', 'food delivery'] },
  ice_cream: { icon: IceCream, keywords: ['ice cream', 'dessert', 'treats', 'sweets'] },
  cake: { icon: Cake, keywords: ['cake', 'birthday', 'bakery', 'party', 'dessert'] },
  sandwich: { icon: Sandwich, keywords: ['sandwich', 'lunch', 'deli', 'takeaway'] },
  popcorn: { icon: Popcorn, keywords: ['popcorn', 'cinema', 'movies', 'snacks'] },
  cookie: { icon: Cookie, keywords: ['cookie', 'biscuits', 'baking', 'snacks', 'treats'] },
  apple: { icon: Apple, keywords: ['apple', 'fruit', 'grocery', 'groceries', 'healthy'] },
  banana: { icon: Banana, keywords: ['banana', 'fruit', 'grocery', 'groceries'] },
  fish: { icon: Fish, keywords: ['fish', 'seafood', 'fishmonger', 'aquarium'] },
  egg: { icon: Egg, keywords: ['egg', 'eggs', 'breakfast', 'grocery'] },
  salad: { icon: Salad, keywords: ['salad', 'healthy', 'diet', 'vegetables', 'lunch'] },
  soup: { icon: Soup, keywords: ['soup', 'meal', 'lunch', 'canteen'] },
  croissant: { icon: Croissant, keywords: ['croissant', 'bakery', 'breakfast', 'pastry'] },

  // ── Sport, fitness & outdoors ──
  bike: { icon: Bike, keywords: ['bike', 'bicycle', 'cycling', 'commute', 'transport'] },
  trophy: { icon: Trophy, keywords: ['trophy', 'sports club', 'competition', 'awards', 'league'] },
  medal: { icon: Medal, keywords: ['medal', 'race', 'running', 'marathon', 'sports club'] },
  target: { icon: Target, keywords: ['target', 'goal', 'archery', 'darts', 'aim'] },
  swords: { icon: Swords, keywords: ['fencing', 'martial arts', 'gaming', 'sword', 'combat sport'] },
  tent: { icon: Tent, keywords: ['tent', 'camping', 'festival', 'outdoors', 'holiday'] },
  mountain: { icon: Mountain, keywords: ['mountain', 'hiking', 'climbing', 'outdoors', 'walking'] },
  mountain_snow: { icon: MountainSnow, keywords: ['skiing', 'snowboarding', 'ski trip', 'winter sports', 'mountain'] },
  waves: { icon: Waves, keywords: ['swimming', 'beach', 'pool', 'surfing', 'sea'] },
  footprints: { icon: Footprints, keywords: ['walking', 'hiking', 'steps', 'running club'] },
  volleyball: { icon: Volleyball, keywords: ['volleyball', 'sports club', 'team sport', 'gym'] },

  // ── Entertainment & hobbies ──
  ticket: { icon: Ticket, keywords: ['ticket', 'event', 'concert', 'cinema', 'theatre', 'booking'] },
  clapperboard: { icon: Clapperboard, keywords: ['cinema', 'movies', 'film', 'streaming'] },
  camera: { icon: Camera, keywords: ['camera', 'photography', 'photos', 'hobby'] },
  palette: { icon: Palette, keywords: ['art', 'painting', 'craft', 'hobby', 'creative'] },
  paintbrush: { icon: Paintbrush, keywords: ['painting', 'art', 'craft', 'hobby', 'decorating'] },
  book: { icon: Book, keywords: ['books', 'reading', 'novel', 'kindle'] },
  book_open: { icon: BookOpen, keywords: ['reading', 'study', 'course', 'textbook', 'learning'] },
  library: { icon: Library, keywords: ['library', 'books', 'study', 'membership'] },
  newspaper: { icon: Newspaper, keywords: ['newspaper', 'news', 'subscription', 'magazine'] },
  radio: { icon: Radio, keywords: ['radio', 'podcast', 'audio'] },
  headphones: { icon: Headphones, keywords: ['headphones', 'music', 'podcast', 'audio', 'streaming'] },
  mic: { icon: Mic, keywords: ['podcast', 'singing', 'karaoke', 'recording'] },
  guitar: { icon: Guitar, keywords: ['guitar', 'music lessons', 'band', 'instrument'] },

  // ── Home, tech & DIY ──
  laptop: { icon: Laptop, keywords: ['laptop', 'computer', 'tech', 'work from home', 'electronics'] },
  monitor: { icon: Monitor, keywords: ['monitor', 'screen', 'computer', 'tech', 'office'] },
  printer: { icon: Printer, keywords: ['printer', 'printing', 'ink', 'office', 'stationery'] },
  hard_drive: { icon: HardDrive, keywords: ['storage', 'backup', 'cloud storage', 'tech'] },
  lightbulb: { icon: Lightbulb, keywords: ['electricity', 'lighting', 'energy', 'ideas'] },
  plug: { icon: Plug, keywords: ['electrics', 'power', 'appliances', 'electrician'] },
  thermometer: { icon: Thermometer, keywords: ['heating', 'temperature', 'boiler', 'weather'] },
  fan: { icon: Fan, keywords: ['fan', 'cooling', 'air conditioning', 'ventilation'] },
  refrigerator: { icon: Refrigerator, keywords: ['fridge', 'freezer', 'appliance', 'kitchen'] },
  washing_machine: { icon: WashingMachine, keywords: ['washing machine', 'laundry', 'appliance'] },
  sofa: { icon: Sofa, keywords: ['sofa', 'furniture', 'living room', 'home'] },
  bed: { icon: Bed, keywords: ['bed', 'furniture', 'bedroom', 'mattress'] },
  lamp: { icon: Lamp, keywords: ['lamp', 'lighting', 'home decor'] },
  hammer: { icon: Hammer, keywords: ['diy', 'tools', 'renovation', 'building', 'handyman'] },
  drill: { icon: Drill, keywords: ['diy', 'tools', 'renovation', 'handyman'] },
  paint_roller: { icon: PaintRoller, keywords: ['decorating', 'painting', 'renovation', 'diy'] },
  ruler: { icon: Ruler, keywords: ['diy', 'measuring', 'renovation', 'stationery'] },

  // ── Beauty & personal care ──
  scissors: { icon: Scissors, keywords: ['haircut', 'hairdresser', 'barber', 'salon'] },
  sparkles: { icon: Sparkles, keywords: ['beauty', 'cosmetics', 'spa', 'nails', 'treatments'] },
  bath: { icon: Bath, keywords: ['spa', 'bath', 'self care', 'wellness'] },

  // ── Family, pets & giving ──
  cat: { icon: Cat, keywords: ['cat', 'pet', 'vet'] },
  dog: { icon: Dog, keywords: ['dog', 'pet', 'vet', 'walking'] },
  bird: { icon: Bird, keywords: ['bird', 'pet', 'aviary'] },
  rabbit: { icon: Rabbit, keywords: ['rabbit', 'pet', 'small animal'] },
  heart_handshake: { icon: HeartHandshake, keywords: ['charity', 'donation', 'giving', 'volunteering'] },
  gift: { icon: Gift, keywords: ['gift', 'present', 'birthday', 'christmas'] },
  party_popper: { icon: PartyPopper, keywords: ['party', 'celebration', 'birthday', 'event'] },

  // ── Finance & work ──
  hand_coins: { icon: HandCoins, keywords: ['allowance', 'pocket money', 'tip', 'donation'] },
  coins: { icon: Coins, keywords: ['coins', 'change', 'petty cash', 'savings'] },
  dollar_sign: { icon: DollarSign, keywords: ['money', 'foreign currency', 'dollars', 'exchange'] },
  pound_sterling: { icon: PoundSterling, keywords: ['money', 'pounds', 'sterling', 'income', 'finance'] },
  trending_up: { icon: TrendingUp, keywords: ['investment', 'growth', 'stocks', 'shares', 'gains'] },
  trending_down: { icon: TrendingDown, keywords: ['losses', 'expenses', 'decline', 'stocks'] },
  bar_chart: { icon: BarChart, keywords: ['budget', 'report', 'analytics', 'statistics'] },
  building: { icon: Building, keywords: ['office', 'work', 'company', 'business'] },
  briefcase: { icon: Briefcase, keywords: ['work', 'business', 'job', 'office', 'career'] },
  package: { icon: Package, keywords: ['parcel', 'delivery', 'post', 'online shopping'] },
  boxes: { icon: Boxes, keywords: ['storage', 'moving', 'boxes', 'removals'] },
  store: { icon: Store, keywords: ['shop', 'retail', 'store', 'high street'] },
  shopping_bag: { icon: ShoppingBag, keywords: ['shopping', 'retail', 'clothes shopping', 'purchase'] },

  // ── Transport ──
  bus: { icon: Bus, keywords: ['bus', 'public transport', 'commute', 'travel'] },
  train: { icon: TrainFront, keywords: ['train', 'rail', 'commute', 'season ticket', 'travel'] },
  ship: { icon: Ship, keywords: ['ferry', 'cruise', 'boat', 'travel'] },
  anchor: { icon: Anchor, keywords: ['boat', 'marina', 'sailing', 'harbour'] },
  sailboat: { icon: Sailboat, keywords: ['sailing', 'boat', 'yacht', 'marina'] },
  parking: { icon: ParkingCircle, keywords: ['parking', 'car park', 'permit'] },

  // ── Nature & weather ──
  sun: { icon: Sun, keywords: ['sunny', 'holiday', 'summer', 'weather'] },
  cloud: { icon: Cloud, keywords: ['cloud storage', 'weather', 'subscription'] },
  snowflake: { icon: Snowflake, keywords: ['winter', 'snow', 'cold', 'ski'] },
  umbrella: { icon: Umbrella, keywords: ['rain', 'weather', 'protection', 'warranty'] },
  flower: { icon: Flower, keywords: ['flowers', 'florist', 'garden', 'gift'] },
  leaf: { icon: Leaf, keywords: ['garden', 'plants', 'eco', 'nature'] },
  tree_pine: { icon: TreePine, keywords: ['garden', 'trees', 'christmas tree', 'nature', 'forest'] },
  bug: { icon: Bug, keywords: ['pest control', 'insects', 'garden'] },

  // ── Life admin ──
  file_text: { icon: FileText, keywords: ['documents', 'paperwork', 'admin', 'contract'] },
  folder: { icon: Folder, keywords: ['files', 'admin', 'documents', 'organisation'] },
  mail: { icon: Mail, keywords: ['post', 'mail', 'letters', 'stamps'] },
  send: { icon: Send, keywords: ['transfer', 'sending money', 'remittance'] },
  message_circle: { icon: MessageCircle, keywords: ['messaging', 'phone plan', 'communication'] },
  calendar: { icon: Calendar, keywords: ['calendar', 'appointment', 'booking', 'planner'] },
  clock: { icon: Clock, keywords: ['time', 'subscription', 'membership', 'schedule'] },
  map_pin: { icon: MapPin, keywords: ['location', 'travel', 'trip', 'navigation'] },
  globe: { icon: Globe, keywords: ['travel', 'abroad', 'international', 'world'] },
  key: { icon: Key, keywords: ['keys', 'locksmith', 'letting', 'deposit', 'rental'] },
  lock: { icon: Lock, keywords: ['security', 'safe', 'lock', 'protection'] },
  shield_check: { icon: ShieldCheck, keywords: ['warranty', 'protection plan', 'guarantee', 'cover'] },
  school: { icon: School, keywords: ['school', 'education', 'tuition', 'fees'] },
  backpack: { icon: Backpack, keywords: ['school', 'university', 'student', 'travel'] },
}

export type ExtendedIconKey = keyof typeof EXTENDED_ICONS
