// Joint cost-splitting, ported to the ledger model. Two things live here:
//  - personShareOfJointAmount: the actual split math, shared by both use
//    sites below.
//  - generateJointContributionTransactions: synthetic, personal-scoped
//    transactions representing ONE person's share of every joint bill/
//    loan occurrence. UAT Batch 4 (2026-09-04): this USED TO be folded
//    into that person's own Personal-ledger projection (projection.ts) —
//    deliberately reversed per Adam's explicit call, the Personal ledger
//    shows nothing about joint bills at all now. This generator's only
//    remaining consumer is salarySortLedger.ts's suggested joint top-up
//    amount ("how much of this cycle's joint bills is MY share"), which
//    is a pure calculation, never displayed as a personal transaction.
//  - computeJointSummary: the Joint card's own view — full joint amounts
//    (not split), plus a per-person contribution breakdown.
//
// ASSUMPTION, same one the pre-rebuild app made: every joint item splits
// between exactly two people (payee + "the other one"), since payee/
// payeeSharePercent is a two-way split by construction (SplitEditor only
// ever offers two people). A household with 3+ people isn't modelled.

import { generateTransactionsForTemplate } from './schedule'
import { generateLoanPaymentTransactions } from './ledgerLoans'
import type { AppDataV2, Transaction, TransferLocation } from '../types/ledger'

const round2 = (n: number) => Math.round(n * 100) / 100

/** This person's share of a joint amount, given who the nominal payee is and their share percent. */
export function personShareOfJointAmount(amount: number, payee: string, payeeSharePercent: number, personId: string): number {
  const percent = personId === payee ? payeeSharePercent : 100 - payeeSharePercent
  return round2(amount * (percent / 100))
}

/**
 * 2026-09-13 (Joint's "Group by Person", Adam-specified) — which person
 * "owns" the NON-joint side of a transfer touching the joint account.
 * Deliberately NOT the same payee/payeeSharePercent split a bill/loan
 * uses — Adam's own words: "Withdrawals and deposits into joint should
 * always have an owner, they're both transfers, so they leave someone's
 * account. Transfers are always 100% assigned to the owner, no split."
 * `TransferLocation`'s own 'personal' variant carries no personId at
 * all (this app has exactly one "Current Account," always the primary
 * person's own — see `buildTransferTransaction`'s `ownerId:
 * primaryPersonId`, hardcoded regardless of who's really on the other
 * end), so 'personal' always resolves to the primary person. A Pot or
 * Savings Pot DOES belong to a specific person (`Pot.personId`/
 * `SavingsPot.personId`), so those resolve to whichever person actually
 * owns that pot — the one case a transfer's owner can genuinely be the
 * SECONDARY person.
 */
export function resolveNonJointTransferOwner(data: AppDataV2, location: TransferLocation, primaryPersonId: string): string {
  if (location.type === 'pot') return (data.pots ?? []).find((p) => p.id === location.potId)?.personId ?? primaryPersonId
  if (location.type === 'savings') return data.savingsPots.find((p) => p.id === location.savingsPotId)?.personId ?? primaryPersonId
  return primaryPersonId
}

/** One bucket in Joint's "Group by Person" view — either a real person's share of bills/loans/transfers, or the unattributed "Spend" bucket. */
export interface JointPersonGroup {
  id: string
  name: string
  transactions: Transaction[]
}

/**
 * Splits the joint ledger's own real transaction list (from
 * `computeJointAccountProjection`) into per-person buckets, PLUS a
 * "Spend" bucket for whatever has no person attribution at all — Adam's
 * own spec, verbatim: "each person and their share of the bills and
 * transfers, and a third row for spend only, which is not person
 * specific, only bills and transfers are grouped by person."
 *
 *  - A joint-located bill/loan occurrence (has a real `payee`) splits by
 *    `personShareOfJointAmount` — the SAME transaction can appear in
 *    BOTH people's lists at their own share amount (e.g. a 50/50 split),
 *    with `amount` overridden to that share; a 0% share is omitted
 *    entirely rather than shown as £0.
 *  - A transfer (or the legacy `joint_deposit`/`joint_withdrawal`
 *    types — never generated by current code, kept only for
 *    already-persisted rows) is 100% attributed to one person via
 *    `resolveNonJointTransferOwner`, unmodified — never split.
 *  - Everything else (ad-hoc `type: 'expense'/'income'` at
 *    `location: 'joint'`, no `payee`) goes into "Spend," unmodified and
 *    unattributed, regardless of who logged it.
 *
 * Never pulls in anything outside `transactions` (the real joint
 * ledger) — no personal-location data of any kind.
 */
export function buildJointPersonGroups(data: AppDataV2, transactions: Transaction[]): JointPersonGroup[] {
  const primaryPersonId = data.primaryPersonId
  const byPerson = new Map<string, Transaction[]>(data.people.map((p) => [p.id, []]))
  const spend: Transaction[] = []

  for (const t of transactions) {
    if (t.type === 'transfer' || t.type === 'joint_deposit' || t.type === 'joint_withdrawal') {
      const owner =
        t.type === 'transfer'
          ? resolveNonJointTransferOwner(data, t.fromLocation?.type === 'joint' ? (t.toLocation ?? { type: 'personal' }) : (t.fromLocation ?? { type: 'personal' }), primaryPersonId)
          : (t.ownerId ?? primaryPersonId)
      ;(byPerson.get(owner) ?? byPerson.get(primaryPersonId))?.push(t)
      continue
    }
    if (t.payee) {
      for (const p of data.people) {
        const share = personShareOfJointAmount(t.amount, t.payee, t.payeeSharePercent ?? 100, p.id)
        if (share > 0) byPerson.get(p.id)?.push({ ...t, amount: share })
      }
      continue
    }
    spend.push(t)
  }

  return [...data.people.map((p) => ({ id: p.id, name: p.name, transactions: byPerson.get(p.id) ?? [] })), { id: 'spend', name: 'Spend', transactions: spend }]
}

/**
 * This person's SHARE of every joint recurring-bill/loan occurrence in
 * the range, as synthetic transactions shaped like a personal one
 * (location: 'personal', ownerId: personId) — not real ledger entries,
 * purely a calculation input for salarySortLedger.ts. NOT folded into
 * any projection any more (see file header).
 */
export function generateJointContributionTransactions(data: AppDataV2, personId: string, rangeStart: Date, rangeEnd: Date): Omit<Transaction, 'id'>[] {
  const results: Omit<Transaction, 'id'>[] = []

  for (const template of data.recurringTemplates.filter((t) => t.location === 'joint')) {
    for (const occ of generateTransactionsForTemplate(template, rangeStart, rangeEnd)) {
      const share = personShareOfJointAmount(occ.amount, template.payee, template.payeeSharePercent, personId)
      if (share <= 0) continue
      results.push({ ...occ, amount: share, location: 'personal', ownerId: personId, note: `Your share of ${template.name}` })
    }
  }

  for (const loan of data.loans.filter((l) => l.location === 'joint')) {
    for (const occ of generateLoanPaymentTransactions(loan, rangeStart, rangeEnd)) {
      const share = personShareOfJointAmount(occ.amount, loan.payee, loan.payeeSharePercent, personId)
      if (share <= 0) continue
      results.push({ ...occ, amount: share, location: 'personal', ownerId: personId, note: `Your share of ${loan.name}` })
    }
  }

  return results
}

export interface JointSummary {
  totalOutgoings: number // full, unsplit joint amounts due in the range
  perPerson: { personId: string; name: string; amount: number }[] // each person's share of that same total
  items: { name: string; amount: number; date: string }[] // individual joint occurrences, for display
}

/** The Joint card's own view: full joint costs, plus who owes what share — the shared account's own picture, distinct from anyone's personal balance. */
export function computeJointSummary(data: AppDataV2, rangeStart: Date, rangeEnd: Date): JointSummary {
  const items: { name: string; amount: number; date: string; payee: string; payeeSharePercent: number }[] = []

  for (const template of data.recurringTemplates.filter((t) => t.location === 'joint')) {
    for (const occ of generateTransactionsForTemplate(template, rangeStart, rangeEnd)) {
      items.push({ name: template.name, amount: occ.amount, date: occ.date, payee: template.payee, payeeSharePercent: template.payeeSharePercent })
    }
  }
  for (const loan of data.loans.filter((l) => l.location === 'joint')) {
    for (const occ of generateLoanPaymentTransactions(loan, rangeStart, rangeEnd)) {
      items.push({ name: loan.name, amount: occ.amount, date: occ.date, payee: loan.payee, payeeSharePercent: loan.payeeSharePercent })
    }
  }

  const totalOutgoings = round2(items.reduce((sum, i) => sum + i.amount, 0))
  const perPerson = data.people.map((p) => ({
    personId: p.id,
    name: p.name,
    amount: round2(items.reduce((sum, i) => sum + personShareOfJointAmount(i.amount, i.payee, i.payeeSharePercent, p.id), 0)),
  }))

  return { totalOutgoings, perPerson, items: items.map(({ name, amount, date }) => ({ name, amount, date })) }
}

/** Every person's share should sum back to the full total (within rounding slack). The single most important property this file needs to hold — exported so tests can check it directly against arbitrary data rather than hand-deriving the expected total. */
export function jointSharesReconcile(summary: JointSummary): boolean {
  const summed = round2(summary.perPerson.reduce((sum, p) => sum + p.amount, 0))
  return Math.abs(summed - summary.totalOutgoings) <= 0.05
}

// SUPERSEDED (Adam-specified, 2026-09-03): householdRealActivity used to
// live here, feeding BOTH the Joint and Household cards with a mixed
// "joint bills + everyone's income" list. Split into two, each scoped to
// what its card actually shows now:
//  - The joint account's own real activity (joint bills paid, deposits/
//    withdrawals) — jointAccountLedger.ts's computeJointAccountProjection.
//  - Each person's personal-only activity for the Household card
//    (joint bills deliberately excluded) — householdLedger.ts's
//    computeHouseholdPersonProjection/computeHouseholdProjections.
// Nothing in this file reads or produces a mixed joint+income list any
// more.

